# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startUpGoggleApp', '0005_businessdirectory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdirectory',
            name='isActive',
            field=models.BooleanField(default='True'),
        ),
    ]
